site_name: Radio System Docs
site_description: 'Documentation for https://github.com/Redon-Tech/Radio-System/'
site_author: 'Redon Tech'
docs_dir: docs/
repo_name: 'Redon-Tech/Radio-System'
repo_url: 'https://github.com/Redon-Tech/Radio-System/'
nav:
    - Home: index.md
    - Setup:
      - Setup Home: setup/index.md
      - Setup: setup/setup.md
      - Configuration: setup/configuration.md
    - Guide:
      - API:
        - Overview: guide/api/index.md
        - Client Wrapper: guide/api/client.md
        - Server Wrapper: guide/api/server.md

copyright: Copyright &copy; 2024 Redon Tech

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Redon-Tech
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Eb384Xw
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/parker02311

theme:
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tabs.link
  name: 'material'
  icon:
    logo: fontawesome/solid/walkie-talkie
  favicon: assets/favicon.png
  custom_dir: docs/assets/overrides
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: catppuccin-latte
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: catppuccin-mocha
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

extra_css:
  - assets/css/theme.css


plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tilde
  - admonition
  - tables
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true