name: Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Foreman
        uses: Roblox/setup-foreman@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Create builds directory
        run: mkdir -p builds

      - name: Build Radio System
        run: rojo build build.project.json -o builds/redon-tech-RADIO-SYSTEM.rbxmx

      - name: Build Client API
        run: rojo build clientapi.project.json -o builds/client-api.rbxmx

      - name: Build Server API
        run: rojo build serverapi.project.json -o builds/server-api.rbxmx

      - name: Upload Files
        run: gh release upload ${{ github.ref_name }} builds/*.rbxmx
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}