name: MkDocs Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "MkDocs Deploy"
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -U -r ./docs-requirements.txt
      - run: mkdocs gh-deploy --force